ALTER TABLE
    schedules
ADD
    COLUMN IF NOT EXISTS day_of_week INTEGER NOT NULL DEFAULT 1,
ADD
    COLUMN IF NOT EXISTS start_time TIME NOT NULL DEFAULT '08:00:00',
ADD
    COLUMN IF NOT EXISTS end_time TIME NOT NULL DEFAULT '09:00:00',
ADD
    COLUMN IF NOT EXISTS appointment_duration_minutes INTEGER NOT NULL DEFAULT 30;

ALTER TABLE
    appointments
ADD
    COLUMN IF NOT EXISTS professional_unit_id TEXT REFERENCES professional_units(id) ON DELETE CASCADE,
ADD
    COLUMN IF NOT EXISTS start_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD
    COLUMN IF NOT EXISTS end_at TIMESTAMP NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS professional_availability_blocks (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    professional_unit_id TEXT NOT NULL REFERENCES professional_units(id) ON DELETE CASCADE,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    reason TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);